import test from "ava";
import check from "./dist/mcgorgeous.common";

const sitesSchema = [
  {
    id: "string",
    site_id: "string",
    state: "string",
    plan: "string",
    name: "string",
    custom_domain: "string",
    domain_aliases: ["string"],
    password: "string",
    notification_email: "string",
    url: "string",
    ssl_url: "string",
    admin_url: "string",
    screenshot_url: "string",
    created_at: "string",
    updated_at: "string",
    user_id: "string",
    session_id: "string",
    ssl: true,
    force_ssl: true,
    managed_dns: true,
    deploy_url: "string",
    published_deploy: {
      id: "string",
      site_id: "string",
      user_id: "string",
      build_id: "string",
      state: "string",
      name: "string",
      url: "string",
      ssl_url: "string",
      admin_url: "string",
      deploy_url: "string",
      deploy_ssl_url: "string",
      screenshot_url: "string",
      review_id: 0,
      draft: true,
      required: ["string"],
      required_functions: ["string"],
      error_message: "string",
      branch: "string",
      commit_ref: "string",
      commit_url: "string",
      skipped: true,
      created_at: "string",
      updated_at: "string",
      published_at: "string",
      title: "string",
      context: "string",
      locked: true,
      review_url: "string",
      site_capabilities: {
        large_media_enabled: true
      }
    },
    account_name: "string",
    account_slug: "string",
    git_provider: "string",
    deploy_hook: "string",
    capabilities: {
      additionalProp1: {},
      additionalProp2: {},
      additionalProp3: {}
    },
    processing_settings: {
      skip: true,
      css: {
        bundle: true,
        minify: true
      },
      js: {
        bundle: true,
        minify: true
      },
      images: {
        optimize: true
      },
      html: {
        pretty_urls: true
      }
    },
    build_settings: {
      id: 0,
      provider: "string",
      deploy_key_id: "string",
      repo_path: "string",
      repo_branch: "string",
      dir: "string",
      cmd: "string",
      allowed_branches: ["string"],
      public_repo: true,
      private_logs: true,
      repo_url: "string",
      env: {
        additionalProp1: "string",
        additionalProp2: "string",
        additionalProp3: "string"
      },
      installation_id: "string"
    },
    id_domain: "string",
    default_hooks_data: {
      access_token: "string"
    },
    build_image: "string",
    repo: {
      id: 0,
      provider: "string",
      deploy_key_id: "string",
      repo_path: "string",
      repo_branch: "string",
      dir: "string",
      cmd: "string",
      allowed_branches: ["string"],
      public_repo: true,
      private_logs: true,
      repo_url: "string",
      env: {
        additionalProp1: "string",
        additionalProp2: "string",
        additionalProp3: "string"
      },
      installation_id: "string"
    }
  }
];

const sitesData = [
  {
    id: "4fe62c79-2afa-4f7b-8fbe-3fd42330a60f",
    site_id: "4fe62c79-2afa-4f7b-8fbe-3fd42330a60f",
    plan: "nf_team_dev",
    plan_data: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      build_cluster: "buildbot-3",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      cdn_network: "free_cdn_network",
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev"
    },
    ssl_plan: null,
    premium: false,
    claimed: true,
    name: "js-netlify-react-ui",
    custom_domain: null,
    domain_aliases: [],
    password: null,
    notification_email: null,
    url: "http://js-netlify-react-ui.netlify.com",
    admin_url: "https://app.netlify.com/sites/js-netlify-react-ui",
    deploy_id: "",
    build_id: "",
    deploy_url: "http://.js-netlify-react-ui.netlify.com",
    state: "current",
    screenshot_url: null,
    created_at: "2019-07-01T19:13:01.312Z",
    updated_at: "2019-07-01T19:13:01.312Z",
    user_id: "5c6d7ac271c928a04e0787c0",
    error_message: null,
    ssl: false,
    ssl_url: "https://js-netlify-react-ui.netlify.com",
    force_ssl: null,
    ssl_status: null,
    max_domain_aliases: 100,
    build_settings: {},
    processing_settings: {
      css: {
        bundle: true,
        minify: true
      },
      js: {
        bundle: true,
        minify: true
      },
      images: {
        optimize: true
      },
      html: {
        pretty_urls: true
      },
      skip: true
    },
    prerender: null,
    prerender_headers: null,
    deploy_hook: null,
    published_deploy: null,
    managed_dns: true,
    jwt_secret: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    account_slug: "jschatz1-uqdjpfq",
    account_name: "Jacob Schatz's team",
    account_type: "personal",
    capabilities: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      build_cluster: "buildbot-3",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      cdn_network: "free_cdn_network",
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev"
    },
    active_subscription_ids: [],
    external_contributors_enabled: false,
    paid_individual_site_subscription: false,
    dns_zone_id: null,
    identity_instance_id: null,
    use_functions: null,
    parent_user_id: null,
    automatic_tls_provisioning: null,
    disabled: null,
    lifecycle_state: "active",
    id_domain: "4fe62c79-2afa-4f7b-8fbe-3fd42330a60f.netlify.com",
    use_lm: null,
    build_image: "xenial",
    has_analytics_data: false,
    analytics_enabled: false,
    automatic_tls_provisioning_expired: false
  },
  {
    id: "ca08f77b-1ae8-4736-89fa-5d796a778197",
    site_id: "ca08f77b-1ae8-4736-89fa-5d796a778197",
    plan: "nf_team_dev",
    plan_data: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      build_cluster: "buildbot-3",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      cdn_network: "free_cdn_network",
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev"
    },
    ssl_plan: null,
    premium: false,
    claimed: true,
    name: "jacob-schatz-react-app",
    custom_domain: null,
    domain_aliases: [],
    password: null,
    notification_email: null,
    url: "http://jacob-schatz-react-app.netlify.com",
    admin_url: "https://app.netlify.com/sites/jacob-schatz-react-app",
    deploy_id: "",
    build_id: "",
    deploy_url: "http://.jacob-schatz-react-app.netlify.com",
    state: "current",
    screenshot_url: null,
    created_at: "2019-07-01T18:55:19.475Z",
    updated_at: "2019-07-01T18:55:19.475Z",
    user_id: "5c6d7ac271c928a04e0787c0",
    error_message: null,
    ssl: false,
    ssl_url: "https://jacob-schatz-react-app.netlify.com",
    force_ssl: null,
    ssl_status: null,
    max_domain_aliases: 100,
    build_settings: {},
    processing_settings: {
      css: {
        bundle: true,
        minify: true
      },
      js: {
        bundle: true,
        minify: true
      },
      images: {
        optimize: true
      },
      html: {
        pretty_urls: true
      },
      skip: true
    },
    prerender: null,
    prerender_headers: null,
    deploy_hook: null,
    published_deploy: null,
    managed_dns: true,
    jwt_secret: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    account_slug: "jschatz1-uqdjpfq",
    account_name: "Jacob Schatz's team",
    account_type: "personal",
    capabilities: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      build_cluster: "buildbot-3",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      cdn_network: "free_cdn_network",
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev"
    },
    active_subscription_ids: [],
    external_contributors_enabled: false,
    paid_individual_site_subscription: false,
    dns_zone_id: null,
    identity_instance_id: null,
    use_functions: null,
    parent_user_id: null,
    automatic_tls_provisioning: null,
    disabled: null,
    lifecycle_state: "active",
    id_domain: "ca08f77b-1ae8-4736-89fa-5d796a778197.netlify.com",
    use_lm: null,
    build_image: "xenial",
    has_analytics_data: false,
    analytics_enabled: false,
    automatic_tls_provisioning_expired: false
  },
  {
    id: "53a1de77-8e9f-4a51-a1e0-a1abefa1a0ae",
    site_id: "53a1de77-8e9f-4a51-a1e0-a1abefa1a0ae",
    plan: "nf_team_dev",
    plan_data: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      build_cluster: "buildbot-3",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      cdn_network: "free_cdn_network",
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev"
    },
    ssl_plan: null,
    premium: false,
    claimed: true,
    name: "the-project",
    custom_domain: null,
    domain_aliases: [],
    password: null,
    notification_email: null,
    url: "http://the-project.netlify.com",
    admin_url: "https://app.netlify.com/sites/the-project",
    deploy_id: "",
    build_id: "",
    deploy_url: "http://.the-project.netlify.com",
    state: "current",
    screenshot_url: null,
    created_at: "2019-07-01T18:45:30.188Z",
    updated_at: "2019-07-01T18:45:30.188Z",
    user_id: "5c6d7ac271c928a04e0787c0",
    error_message: null,
    ssl: false,
    ssl_url: "https://the-project.netlify.com",
    force_ssl: null,
    ssl_status: null,
    max_domain_aliases: 100,
    build_settings: {},
    processing_settings: {
      css: {
        bundle: true,
        minify: true
      },
      js: {
        bundle: true,
        minify: true
      },
      images: {
        optimize: true
      },
      html: {
        pretty_urls: true
      },
      skip: true
    },
    prerender: null,
    prerender_headers: null,
    deploy_hook: null,
    published_deploy: null,
    managed_dns: true,
    jwt_secret: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    account_slug: "jschatz1-uqdjpfq",
    account_name: "Jacob Schatz's team",
    account_type: "personal",
    capabilities: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      build_cluster: "buildbot-3",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      cdn_network: "free_cdn_network",
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev"
    },
    active_subscription_ids: [],
    external_contributors_enabled: false,
    paid_individual_site_subscription: false,
    dns_zone_id: null,
    identity_instance_id: null,
    use_functions: null,
    parent_user_id: null,
    automatic_tls_provisioning: null,
    disabled: null,
    lifecycle_state: "active",
    id_domain: "53a1de77-8e9f-4a51-a1e0-a1abefa1a0ae.netlify.com",
    use_lm: null,
    build_image: "xenial",
    has_analytics_data: false,
    analytics_enabled: false,
    automatic_tls_provisioning_expired: false
  }
];

test("foo", t => {
  const checkData = check(sitesSchema, sitesData);
  console.log("check.message", checkData.message, checkData.info);
  t.true(checkData.result);
});
